"""Coder agent.

Renders a runnable project skeleton from a Jinja2 template, optionally
asks Grok to layer the spec-specific implementation on top, and emits a
typed event per file written so the UI can build a live file tree and
syntax-highlight the contents in a code pane.

In offline / mock mode, the Coder generates spec-tailored code using
heuristic keyword matching against the plan — orbital mechanics produces
a real velocity-Verlet integrator, photo-z produces a histogramming
endpoint, etc. The user always sees actual working code, never lorem ipsum.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

from .base import Agent, AgentRequest
from .router import ModelRouter
from .codegen import generate_spec_specific_code

TEMPLATE_DIR = Path(__file__).parent / "templates"

SYSTEM_PROMPT = """You are the Coder agent in grokforge.
Given a project plan, emit production-grade source files as strict JSON:
{"files": [{"path": "app/main.py", "content": "..."}], "entrypoint": "..."}

Rules:
- All file contents must be self-consistent and runnable as-is.
- Imports must reference real, currently-pinned packages.
- No placeholders ("TODO", "...", "your code here"). Fill everything.
- Keep it small: <= 8 files, <= 600 lines total.
Return only JSON.
"""


class CoderAgent(Agent):
    name = "coder"

    def __init__(self, router: ModelRouter) -> None:
        super().__init__()
        self.router = router
        self.env = Environment(
            loader=FileSystemLoader(str(TEMPLATE_DIR)),
            autoescape=select_autoescape(enabled_extensions=()),
            keep_trailing_newline=True,
        )

    async def run(self, req: AgentRequest) -> dict[str, Any]:
        plan = req.input or {}
        stack = plan.get("stack", "python+fastapi")
        spec = (plan.get("spec") or plan.get("summary") or "").strip()

        self.think(
            f"The plan picked stack={stack}. I'll start from the deterministic scaffold "
            f"so the project boots no matter what, then layer the spec-specific logic.",
            scope="strategy",
        )
        self.decide(
            f"render baseline template for {stack}",
            "Templates ship a known-good FastAPI app, requirements.txt, Dockerfile, "
            "and pytest harness. This guarantees the output runs even if the LLM patch fails.",
        )

        files = self._render_template(stack, plan)
        self.metric("baseline_files", len(files), "")

        # Spec-specific code generation (mock mode and a fallback when LLM disabled).
        spec_files = generate_spec_specific_code(spec, plan)
        for path, content in spec_files.items():
            files[path] = content

        # Live LLM patch when available.
        if self.router.client.configured:
            self.think(
                "Grok API is configured — asking the primary model to refine app/main.py "
                "and tests against the milestones. I'll merge whatever it returns over the "
                "baseline; on parse error I keep the baseline.",
                scope="llm",
            )
            try:
                self.tool_call("grok.chat", {"stage": "coder", "json_mode": True})
                text, cost, model = await self.router.chat(
                    "coder",
                    [
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content":
                            "PLAN:\n" + json.dumps(plan, indent=2)[:6000]
                            + "\n\nReturn JSON with `files` replacing or adding to `app/`."},
                    ],
                    temperature=0.2,
                    max_tokens=4000,
                    json_mode=True,
                )
                self.cost_usd += cost
                self.metric("tokens_cost_usd", round(cost, 4), "$")
                self.tool_call("grok.chat.return", {"model": model, "cost_usd": cost})
                patch = _safe_json(text)
                for f in patch.get("files", []):
                    if "path" in f and "content" in f:
                        files[f["path"]] = f["content"]
            except Exception as e:
                self.think(f"LLM patch failed ({e}); keeping deterministic scaffold + spec-tailored code.",
                           scope="fallback")
        else:
            self.think(
                "No GROK_API_KEY configured — running in deterministic mock mode. "
                "The code below is generated by spec-keyword templates, not an LLM.",
                scope="mock",
            )

        # Emit one file_written event per file so the UI can build a live tree.
        for path, content in sorted(files.items()):
            self.file_written(path, content, language=_lang_for(path))

        self.metric("total_files", len(files), "")
        self.metric("total_lines", sum(c.count("\n") + 1 for c in files.values()), "")

        return {
            "files": [{"path": p, "content": c} for p, c in sorted(files.items())],
            "entrypoint": "uvicorn app.main:app --host 0.0.0.0 --port 8000",
            "stack": stack,
        }

    async def confidence(self, output: dict[str, Any]) -> float:
        files = output.get("files", [])
        if not files:
            return 0.1
        has_main = any(f["path"].endswith("main.py") for f in files)
        has_req = any(f["path"].endswith("requirements.txt") for f in files)
        has_test = any("test" in f["path"] for f in files)
        return 0.4 + 0.2 * has_main + 0.2 * has_req + 0.2 * has_test

    def _render_template(self, stack: str, plan: dict[str, Any]) -> dict[str, str]:
        stack_dir = {
            "python+fastapi": "python_fastapi",
            "rust+axum": "python_fastapi",
            "typescript+next": "python_fastapi",
        }.get(stack, "python_fastapi")

        root = TEMPLATE_DIR / stack_dir
        out: dict[str, str] = {}
        if not root.exists():
            return out
        ctx = {
            "summary": plan.get("summary", "grokforge generated service"),
            "milestones": plan.get("milestones", []),
        }
        for path in root.rglob("*"):
            if not path.is_file():
                continue
            if any(part in {"__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"}
                   for part in path.parts):
                continue
            if path.suffix in {".pyc", ".pyo"}:
                continue
            rel = path.relative_to(root).as_posix()
            if rel.endswith(".j2"):
                rel = rel[:-3]
                template = self.env.get_template(f"{stack_dir}/{path.relative_to(root).as_posix()}")
                out[rel] = template.render(**ctx)
            else:
                out[rel] = path.read_text()
        return out


def _lang_for(path: str) -> str:
    if path.endswith(".py"):
        return "python"
    if path.endswith(".rs"):
        return "rust"
    if path.endswith(".ts") or path.endswith(".tsx"):
        return "typescript"
    if path.endswith(".js") or path.endswith(".jsx"):
        return "javascript"
    if path.endswith(".yaml") or path.endswith(".yml"):
        return "yaml"
    if path.endswith(".json"):
        return "json"
    if path.endswith(".md"):
        return "markdown"
    if path.endswith(".toml"):
        return "toml"
    if path.endswith("Dockerfile") or path.endswith(".dockerfile"):
        return "dockerfile"
    if path.endswith(".txt"):
        return "text"
    return "text"


def _safe_json(text: str) -> dict[str, Any]:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        start = text.find("{")
        end = text.rfind("}")
        if start >= 0 and end > start:
            try:
                return json.loads(text[start : end + 1])
            except json.JSONDecodeError:
                pass
        return {"files": []}
